name: Deploy dev

on:
  push:
    branches: ["ur-mom"]

env:
  REGISTRY: ghcr.io

jobs:
  python_pytest_flake8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Clean
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: PyTest with Coverage Report
        run: python -m coverage run -m pytest

      - name: Print Coverage report
        run: python -m coverage report

  integration_test:
    runs-on: ubuntu-latest
    needs:
      - python_pytest_flake8
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask server
        run: nohup flask run
        #run: FLASK_APP=hello_flask flask run

      - name: Curl Flask server
        run: curl http://127.0.0.1:5000
